package POJO;

// Generated Mar 22, 2014 10:38:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private String categoryId;
	private Categories categories;
	private String categoryName;
	private Set bookses = new HashSet(0);
	private Set categorieses = new HashSet(0);

	public Categories() {
	}

	public Categories(String categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	public Categories(String categoryId, Categories categories,
			String categoryName, Set bookses, Set categorieses) {
		this.categoryId = categoryId;
		this.categories = categories;
		this.categoryName = categoryName;
		this.bookses = bookses;
		this.categorieses = categorieses;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public Set getBookses() {
		return this.bookses;
	}

	public void setBookses(Set bookses) {
		this.bookses = bookses;
	}

	public Set getCategorieses() {
		return this.categorieses;
	}

	public void setCategorieses(Set categorieses) {
		this.categorieses = categorieses;
	}

}
